// export const DATA_ENDPOINT = `http://35.198.207.97:8000/products/amazon_products/`;
// export const SUMMARY_ENDPOINT = `http://35.198.207.97:8000/products/data_summary/`;
// export const LOGIN_ENDPOINT = `http://35.198.207.97:8000/auth/login/`;
export const BASE_URL = 'http://127.0.0.1:8000';
export const ALL_PRODUCT_ENDPOINT = `${BASE_URL}/products/amazon_products/`
export const SINGLE_PRODUCT_ENDPOINT = `${BASE_URL}/products/single_product/`
export const SUMMARY_ENDPOINT = `${BASE_URL}/products/data_summary/`
export const LOGIN_ENDPOINT = `${BASE_URL}/auth/api/token/`
export const REGISTER_ENDPOINT = `${BASE_URL}/auth/api/register/`
export const REFRESH_TOKEN_ENDPOINT = `${BASE_URL}/api/token/refresh/`;
export const ADD_TO_CART_ENPOINT = `${BASE_URL}/auth/cart`
export const UPDATE_CART_ENPOINT = `${BASE_URL}/auth/cart/`
export const REMOVE_FROM_CART_ENPOINT = `${BASE_URL}/auth/cart/remove/`
export const CLEAR_CART_ENPOINT = `${BASE_URL}/auth/cart/clear/`
